import pytest
import emoji
from unittest.mock import Mock, patch

from core.services.content_quality_filter import (
    EmojiDetector,
    BotCommentDetector,
    BoilerplateDetector,
    ContentTypeHandler,
    ContentQualityFilter
)


@pytest.mark.unit
class TestEmojiDetector:
    def test_is_emoji_only_with_emoji_only(self):
        detector = EmojiDetector()
        assert detector.is_emoji_only('👍') is True

    def test_is_emoji_only_with_plus_one(self):
        detector = EmojiDetector()
        assert detector.is_emoji_only('+1') is True

    def test_is_emoji_only_with_text(self):
        detector = EmojiDetector()
        assert detector.is_emoji_only('Hello world') is False

    def test_is_emoji_only_with_mixed_content(self):
        detector = EmojiDetector()
        assert detector.is_emoji_only('Hello 👍') is False

    def test_is_emoji_only_with_empty_string(self):
        detector = EmojiDetector()
        assert detector.is_emoji_only('') is False

    def test_is_emoji_only_with_whitespace(self):
        detector = EmojiDetector()
        assert detector.is_emoji_only('   ') is False

    def test_is_emoji_only_with_multiple_emojis(self):
        detector = EmojiDetector()
        assert detector.is_emoji_only('👍🎉❤️') is True

    def test_remove_emojis(self):
        detector = EmojiDetector()
        result = detector.remove_emojis('Hello 👍 world')
        assert result == 'Hello world'

    def test_remove_emojis_removes_plus_one(self):
        detector = EmojiDetector()
        result = detector.remove_emojis('Thanks +1')
        assert result == 'Thanks'

    def test_remove_emojis_with_empty_string(self):
        detector = EmojiDetector()
        result = detector.remove_emojis('')
        assert result == ''

    def test_remove_emojis_with_whitespace(self):
        detector = EmojiDetector()
        result = detector.remove_emojis('   ')
        assert result == '   '

    def test_remove_emojis_normalizes_whitespace(self):
        detector = EmojiDetector()
        result = detector.remove_emojis('Hello   👍   world')
        assert result == 'Hello world'


@pytest.mark.unit
class TestBotCommentDetector:
    def test_is_bot_comment_with_bot_author(self):
        detector = BotCommentDetector()
        assert detector.is_bot_comment(author='dependabot[bot]') is True

    def test_is_bot_comment_with_codecov_author(self):
        detector = BotCommentDetector()
        assert detector.is_bot_comment(author='codecov[bot]') is True

    def test_is_bot_comment_with_github_actions_author(self):
        detector = BotCommentDetector()
        assert detector.is_bot_comment(author='github-actions[bot]') is True

    def test_is_bot_comment_with_bot_content(self):
        detector = BotCommentDetector()
        assert detector.is_bot_comment(content='This PR was merged') is True

    def test_is_bot_comment_with_build_passed_content(self):
        detector = BotCommentDetector()
        assert detector.is_bot_comment(content='Build passed') is True

    def test_is_bot_comment_with_ci_cd_content(self):
        detector = BotCommentDetector()
        assert detector.is_bot_comment(content='CI/CD pipeline') is True

    def test_is_bot_comment_with_normal_author(self):
        detector = BotCommentDetector()
        assert detector.is_bot_comment(author='john-doe') is False

    def test_is_bot_comment_with_normal_content(self):
        detector = BotCommentDetector()
        assert detector.is_bot_comment(content='This looks good to me') is False

    def test_is_bot_comment_with_none_author_and_content(self):
        detector = BotCommentDetector()
        assert detector.is_bot_comment() is False

    def test_is_bot_comment_case_insensitive(self):
        detector = BotCommentDetector()
        assert detector.is_bot_comment(author='DEPENDABOT[bot]') is True

    def test_is_bot_comment_with_merge_conflict(self):
        detector = BotCommentDetector()
        assert detector.is_bot_comment(content='Merge conflict detected') is True


@pytest.mark.unit
class TestBoilerplateDetector:
    def test_is_boilerplate_with_copyright(self):
        detector = BoilerplateDetector()
        assert detector.is_boilerplate_content('Copyright 2024 Company') is True

    def test_is_boilerplate_with_all_rights_reserved(self):
        detector = BoilerplateDetector()
        assert detector.is_boilerplate_content('All rights reserved') is True

    def test_is_boilerplate_with_licensed_under(self):
        detector = BoilerplateDetector()
        assert detector.is_boilerplate_content('Licensed under MIT') is True

    def test_is_boilerplate_with_generated_by(self):
        detector = BoilerplateDetector()
        assert detector.is_boilerplate_content('Generated by tool') is True

    def test_is_boilerplate_with_do_not_edit(self):
        detector = BoilerplateDetector()
        assert detector.is_boilerplate_content('DO NOT EDIT THIS FILE') is True

    def test_is_boilerplate_with_template_comment(self):
        detector = BoilerplateDetector()
        assert detector.is_boilerplate_content('# This is a template file') is True

    def test_is_boilerplate_with_normal_content(self):
        detector = BoilerplateDetector()
        assert detector.is_boilerplate_content('This is normal code') is False

    def test_is_boilerplate_with_empty_string(self):
        detector = BoilerplateDetector()
        assert detector.is_boilerplate_content('') is False

    def test_is_boilerplate_with_whitespace(self):
        detector = BoilerplateDetector()
        assert detector.is_boilerplate_content('   ') is False

    def test_is_boilerplate_with_java_import(self):
        detector = BoilerplateDetector()
        assert detector.is_boilerplate_content('import java.util.List;') is True

    def test_is_boilerplate_with_python_import(self):
        detector = BoilerplateDetector()
        assert detector.is_boilerplate_content('from typing import List') is True

    def test_is_boilerplate_case_insensitive(self):
        detector = BoilerplateDetector()
        assert detector.is_boilerplate_content('COPYRIGHT 2024') is True


@pytest.mark.unit
class TestContentTypeHandler:
    def test_init(self):
        boilerplate_detector = BoilerplateDetector()
        handler = ContentTypeHandler(boilerplate_detector)

        assert handler.boilerplate_detector == boilerplate_detector
        assert 'text' in handler._content_handlers
        assert 'file' in handler._content_handlers
        assert 'github_issue' in handler._content_handlers
        assert 'github_pr' in handler._content_handlers

    def test_should_ingest_text_normal_content(self):
        boilerplate_detector = BoilerplateDetector()
        handler = ContentTypeHandler(boilerplate_detector)

        assert handler._should_ingest_text('This is normal text') is True

    def test_should_ingest_text_boilerplate_content(self):
        boilerplate_detector = BoilerplateDetector()
        handler = ContentTypeHandler(boilerplate_detector)

        assert handler._should_ingest_text('Copyright 2024') is False

    def test_should_ingest_file_normal_content(self):
        boilerplate_detector = BoilerplateDetector()
        handler = ContentTypeHandler(boilerplate_detector)

        assert handler._should_ingest_file('def function():\n    pass') is True

    def test_should_ingest_file_boilerplate_content(self):
        boilerplate_detector = BoilerplateDetector()
        handler = ContentTypeHandler(boilerplate_detector)

        assert handler._should_ingest_file('Copyright 2024') is False

    def test_should_ingest_file_header_comment_block(self):
        boilerplate_detector = BoilerplateDetector()
        handler = ContentTypeHandler(boilerplate_detector)

        content = '/**\n * @file\n * @brief\n */'
        assert handler._should_ingest_file(content) is False

    def test_should_ingest_file_python_docstring(self):
        boilerplate_detector = BoilerplateDetector()
        handler = ContentTypeHandler(boilerplate_detector)

        content = '"""Module docstring"""'
        assert handler._should_ingest_file(content) is False

    def test_should_ingest_file_generated_marker(self):
        boilerplate_detector = BoilerplateDetector()
        handler = ContentTypeHandler(boilerplate_detector)

        content = '# This file is generated'
        assert handler._should_ingest_file(content) is False

    def test_should_ingest_github_issue(self):
        boilerplate_detector = BoilerplateDetector()
        handler = ContentTypeHandler(boilerplate_detector)

        assert handler._should_ingest_github_issue('Any content') is True

    def test_should_ingest_github_pr(self):
        boilerplate_detector = BoilerplateDetector()
        handler = ContentTypeHandler(boilerplate_detector)

        assert handler._should_ingest_github_pr('Any content') is True

    def test_should_ingest_content_type_text(self):
        boilerplate_detector = BoilerplateDetector()
        handler = ContentTypeHandler(boilerplate_detector)

        assert handler.should_ingest_content_type('Normal text', 'text') is True

    def test_should_ingest_content_type_file(self):
        boilerplate_detector = BoilerplateDetector()
        handler = ContentTypeHandler(boilerplate_detector)

        assert handler.should_ingest_content_type('def foo():', 'file') is True

    def test_should_ingest_content_type_unknown_defaults_to_text(self):
        boilerplate_detector = BoilerplateDetector()
        handler = ContentTypeHandler(boilerplate_detector)

        assert handler.should_ingest_content_type('Normal text', 'unknown') is True


@pytest.mark.unit
class TestContentQualityFilter:
    def test_init(self):
        filter = ContentQualityFilter()

        assert filter.emoji_detector is not None
        assert filter.bot_detector is not None
        assert filter.boilerplate_detector is not None
        assert filter.content_type_handler is not None

    def test_calculate_quality_score_empty_content(self):
        filter = ContentQualityFilter()
        assert filter.calculate_quality_score('') == 0.0

    def test_calculate_quality_score_short_content(self):
        filter = ContentQualityFilter()
        score = filter.calculate_quality_score('Hi')
        assert score == 0.3

    def test_calculate_quality_score_long_content(self):
        filter = ContentQualityFilter()
        score = filter.calculate_quality_score('This is a longer message')
        assert score >= 0.4

    def test_calculate_quality_score_with_filler_words(self):
        filter = ContentQualityFilter()
        score = filter.calculate_quality_score('thanks thank you lgmt ack nice good great')
        assert score == 0.4

    def test_calculate_quality_score_with_meaningful_words(self):
        filter = ContentQualityFilter()
        score = filter.calculate_quality_score('This function fixes the API error')
        assert score >= 0.7

    def test_calculate_quality_score_max_score(self):
        filter = ContentQualityFilter()
        score = filter.calculate_quality_score('This function fixes the API error in the code implementation')
        assert score == 1.0

    def test_should_ingest_emoji_only(self):
        filter = ContentQualityFilter()
        assert filter.should_ingest('👍') is False

    def test_should_ingest_bot_comment(self):
        filter = ContentQualityFilter()
        assert filter.should_ingest('This PR was merged') is False

    def test_should_ingest_bot_author(self):
        filter = ContentQualityFilter()
        assert filter.should_ingest('Normal comment', author='dependabot[bot]') is False

    def test_should_ingest_normal_content(self):
        filter = ContentQualityFilter()
        assert filter.should_ingest('This is a normal comment') is True

    def test_should_ingest_boilerplate_content(self):
        filter = ContentQualityFilter()
        assert filter.should_ingest('Copyright 2024', content_type='text') is False

    def test_should_ingest_file_header(self):
        filter = ContentQualityFilter()
        content = '/**\n * @file\n */'
        assert filter.should_ingest(content, content_type='file') is False

    def test_should_ingest_github_issue(self):
        filter = ContentQualityFilter()
        assert filter.should_ingest('Issue description', content_type='github_issue') is True

    def test_should_ingest_github_pr(self):
        filter = ContentQualityFilter()
        assert filter.should_ingest('PR description', content_type='github_pr') is True

    def test_remove_emojis(self):
        filter = ContentQualityFilter()
        result = filter.remove_emojis('Hello 👍 world')
        assert result == 'Hello world'
