import re
import logging
import emoji

logger = logging.getLogger(__name__)


class EmojiDetector:
    @staticmethod
    def is_emoji_only(content: str) -> bool:
        if not content or not content.strip():
            return False

        content_clean = re.sub(r'\s+', '', content)

        if content_clean == '+1':
            return True

        emoji_chars = emoji.emoji_list(content_clean)

        if not emoji_chars:
            return False

        covered_chars = 0
        for emoji_info in emoji_chars:
            covered_chars += emoji_info['match_end'] - emoji_info['match_start']

        return covered_chars == len(content_clean)

    @staticmethod
    def remove_emojis(content: str) -> str:
        if not content or not content.strip():
            return content

        cleaned = emoji.replace_emoji(content, replace='')
        cleaned = re.sub(r'\+1', '', cleaned)
        cleaned = re.sub(r'\s+', ' ', cleaned).strip()
        return cleaned


class BotCommentDetector:
    def __init__(self):
        self.bot_patterns = [
            r'dependabot(\[bot\])?',
            r'codecov(\[bot\])?',
            r'github-actions(\[bot\])?',
            r'cla-assistant(\[bot\])?',
            r'snyk(\[bot\])?',
            r'pull-request-review(\[bot\])?',
            r'sonarcloud(\[bot\])?',
            r'codacy(\[bot\])?',
            r'coveralls(\[bot\])?',
            r'this pr was merged',
            r'this pull request was merged',
            r'auto-merge',
            r'merge conflict',
            r'ci/cd',
            r'build passed',
            r'build failed',
            r'tests passed',
            r'tests failed'
        ]

    def is_bot_comment(self, author: str = None, content: str = None) -> bool:
        if not content and not author:
            return False

        if author:
            author_lower = author.lower()
            for pattern in self.bot_patterns:
                if re.search(pattern, author_lower, re.IGNORECASE):
                    logger.debug(f"[BotDetector] Detected bot author: {author}")
                    return True

        if content:
            content_lower = content.lower()
            for pattern in self.bot_patterns:
                if re.search(pattern, content_lower, re.IGNORECASE):
                    logger.debug(f"[BotDetector] Detected bot content: {content[:50]}...")
                    return True

        return False


class BoilerplateDetector:
    def __init__(self):
        self.boilerplate_patterns = [
            r'^copyright\s+\d{4}',
            r'^all rights reserved',
            r'^licensed under',
            r'^mit license',
            r'^apache license',
            r'^gpl license',
            r'^this file is part of',
            r'^generated by',
            r'^do not edit',
            r'^this is an auto',
            r'^#.*template',
            r'^import.*from.*__future__',
            r'^#.*coding[:=]\s*utf-8',
            r'^#.*eslint',
            r'^#.*prettier',
            r'^\s*[*\s]*\@file',
            r'^\s*[*\s]*\@brief',
            r'^\s*[*\s]*\@author',
            r'^\s*[*\s]*\@date',
            r'^\s*[*\s]*\@version',
            r'^/\*\*.*\*/',
            r'^<!--.*-->',
            r'^<\?xml',
            r'^<!doctype html',
            r'^<html',
            r'^package\s+',
            r'^import\s+java\.',
            r'^import\s+org\.',
            r'^import\s+com\.',
            r'^using\s+System\.',
            r'^using\s+Microsoft\.',
            r'^#include\s+<',
            r'^from\s+.*import\s+.*',
            r'^require\(',
        ]

    def is_boilerplate_content(self, content: str) -> bool:
        if not content or not content.strip():
            return False

        content_lower = content.lower().strip()

        for pattern in self.boilerplate_patterns:
            if re.search(pattern, content_lower, re.IGNORECASE | re.MULTILINE):
                return True

        return False


class ContentTypeHandler:
    def __init__(self, boilerplate_detector: BoilerplateDetector):
        self.boilerplate_detector = boilerplate_detector
        self._content_handlers = {
            'text': self._should_ingest_text,
            'file': self._should_ingest_file,
            'github_issue': self._should_ingest_github_issue,
            'github_pr': self._should_ingest_github_pr,
        }

    def _should_ingest_text(self, content: str, author: str = None) -> bool:
        if self.boilerplate_detector.is_boilerplate_content(content):
            logger.info(f"[QualityFilter] Skipping boilerplate text content: {content[:50]}...")
            return False
        return True

    def _should_ingest_file(self, content: str, author: str = None) -> bool:
        if self.boilerplate_detector.is_boilerplate_content(content):
            logger.info(f"[QualityFilter] Skipping boilerplate file content: {content[:50]}...")
            return False
        return True

    def _should_ingest_github_issue(self, content: str, author: str = None) -> bool:
        return True

    def _should_ingest_github_pr(self, content: str, author: str = None) -> bool:
        return True

    def should_ingest_content_type(self, content: str, content_type: str = 'text', author: str = None) -> bool:
        handler = self._content_handlers.get(content_type, self._should_ingest_text)
        return handler(content, author)


class ContentQualityFilter:
    def __init__(self):
        logger.debug("[ContentQualityFilter] Initialized with modular filtering")
        self.emoji_detector = EmojiDetector()
        self.bot_detector = BotCommentDetector()
        self.boilerplate_detector = BoilerplateDetector()
        self.content_type_handler = ContentTypeHandler(self.boilerplate_detector)

    def should_ingest(self, content: str, content_type: str = 'text', author: str = None) -> bool:
        if self.emoji_detector.is_emoji_only(content):
            logger.info(f"[QualityFilter] Skipping emoji-only content: {content[:50]}...")
            return False

        if self.bot_detector.is_bot_comment(author=author, content=content):
            logger.info(f"[QualityFilter] Skipping bot/automated content: {content[:50]}...")
            return False

        return self.content_type_handler.should_ingest_content_type(content, content_type, author)

    def remove_emojis(self, content: str) -> str:
        return self.emoji_detector.remove_emojis(content)
