# Generated by Django 5.2.3 on 2026-04-13 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationwidgettoken',
            name='rate_limit_count',
            field=models.PositiveIntegerField(default=60, help_text='Number of requests allowed per period'),
        ),
        migrations.AddField(
            model_name='applicationwidgettoken',
            name='rate_limit_period',
            field=models.PositiveIntegerField(default=60, help_text='Time period in seconds'),
        ),
    ]
