# Generated by Django 5.2.3 on 2025-08-15 15:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppIntegration',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_integrations', to='core.application')),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_integrations', to='core.integration')),
            ],
            options={
                'unique_together': {('application', 'integration')},
            },
        ),
    ]
