# Generated by Django 5.2.3 on 2026-04-01 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vcrepository',
            name='provider',
            field=models.CharField(choices=[('github', 'GitHub'), ('github_graphql', 'GitHub GraphQL')], default='github', max_length=20),
        ),
    ]
