# Generated by Django 5.2.3 on 2026-04-26 17:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_applicationwidgettoken_rate_limit_count_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatroomClientProfile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('sender_identifier', models.CharField(blank=True, max_length=255, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('region', models.CharField(blank=True, max_length=128, null=True)),
                ('city', models.CharField(blank=True, max_length=128, null=True)),
                ('browser', models.CharField(blank=True, max_length=128, null=True)),
                ('domain', models.CharField(blank=True, max_length=255, null=True)),
                ('device_type', models.CharField(blank=True, max_length=64, null=True)),
                ('timezone', models.CharField(blank=True, max_length=128, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chatroom', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client_profile', to='core.chatroom')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
