# Generated by Django 5.2.3 on 2025-08-28 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_appintegration'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='appmodel',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='appmodel',
            name='purpose',
        ),
    ]
