# Generated by Django 5.2.3 on 2025-07-19 16:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_chatroom_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgebase',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='knowledgebase',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('extracting', 'Extracting'), ('processing', 'Processing'), ('processed', 'Processed'), ('reprocessing', 'Reprocessing')], default='pending', help_text='Processing status of the knowledge base item.', max_length=20),
        ),
        migrations.AddField(
            model_name='knowledgebase',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='knowledgebase',
            name='source_type',
            field=models.CharField(choices=[('url', 'URL'), ('file', 'File'), ('text', 'Text')], default='file', max_length=20),
        ),
    ]
