# Generated by Django 5.2.3 on 2026-04-01 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_vcrepository_provider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vcrepository',
            name='provider',
            field=models.CharField(choices=[('github_graphql', 'GitHub GraphQL')], default='github_graphql', max_length=20),
        ),
    ]
