# Generated by Django 5.2.3 on 2025-08-29 12:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_appmodel_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='llmmodel',
            name='api_key_preview',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='llmmodel',
            name='api_key',
            field=models.CharField(default=False, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='llmmodel',
            name='base_url',
            field=models.URLField(default=django.utils.timezone.now, max_length=500),
            preserve_default=False,
        ),
    ]
