# Generated by Django 5.2.3 on 2026-04-01 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_vcrepository_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='escalated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='escalation_cooldown_hours',
            field=models.IntegerField(default=24),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='is_escalated',
            field=models.BooleanField(default=False),
        ),
    ]
