# Generated by Django 5.2.3 on 2026-04-26 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_chatroomclientprofile'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                ALTER TABLE core_message
                ADD COLUMN IF NOT EXISTS is_authenticated_user boolean;

                UPDATE core_message
                SET is_authenticated_user = FALSE
                WHERE is_authenticated_user IS NULL;

                ALTER TABLE core_message
                ALTER COLUMN is_authenticated_user SET DEFAULT FALSE;

                ALTER TABLE core_message
                ALTER COLUMN is_authenticated_user SET NOT NULL;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='message',
                    name='is_authenticated_user',
                    field=models.BooleanField(default=False),
                ),
            ],
            database_operations=[],
        ),
    ]
