# Generated by Django 5.2.3 on 2026-04-03 05:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_vcrepository_provider'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentHash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_hash', models.CharField(max_length=64)),
                ('content_type', models.CharField(max_length=20)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.application')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['app', 'content_hash'], name='core_conten_app_id_939c46_idx')],
                'unique_together': {('app', 'content_hash')},
            },
        ),
    ]
