# Generated by Django 5.2.3 on 2025-07-22 10:45

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_knowledgebase_created_at_knowledgebase_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationAPIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('hashed_api_key', models.CharField(max_length=255)),
                ('permissions', models.JSONField(default=list)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to='core.application')),
            ],
        ),
    ]
