# Generated by Django 5.2.3 on 2025-08-29 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_llmmodel_api_key_preview_alter_llmmodel_api_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appmodel',
            name='llm_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application_configs', to='core.llmmodel'),
        ),
    ]
