# Generated by Django 5.2.3 on 2025-06-18 17:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='sender_identifier',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
