# Generated by Django 5.2.3 on 2026-04-03 05:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_contenthash'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentQualityScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.CharField(max_length=20)),
                ('quality_factors', models.JSONField()),
                ('min_score', models.FloatField(default=0.3)),
            ],
            options={
                'ordering': ['content_type'],
            },
        ),
    ]
