# Generated by Django 5.2.3 on 2025-07-28 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_applicationapikey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowledgebase',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('uploading', 'Uploading'), ('extracting', 'Extracting'), ('processing', 'Processing'), ('processed', 'Processed'), ('reprocessing', 'Reprocessing'), ('failed', 'Failed'), ('completed', 'Completed')], default='pending', help_text='Processing status of the knowledge base item.', max_length=20),
        ),
    ]
