# Generated by Django 5.2.3 on 2025-06-20 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_message_sender_identifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroomparticipant',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('ai_agent', 'AI Agent'), ('human_agent', 'Human Agent')], default='user', max_length=15),
        ),
    ]
