# Generated by Django 5.2.3 on 2025-07-31 18:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_knowledgebase_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Integration',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('provider', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('project_management', 'Project Management'), ('crm', 'CRM'), ('other', 'Other')], max_length=50)),
                ('config', models.JSONField()),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integrations', to='core.application')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
