# Generated by Django 5.2.3 on 2025-07-28 18:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_knowledgebase_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationProfile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('type', models.CharField(choices=[('email', 'Email'), ('slack', 'Slack'), ('discord', 'Discord'), ('whatsapp', 'WhatsApp')], max_length=20)),
                ('config', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
