# Generated by Django 5.2.3 on 2026-04-03 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_escalation_fields_to_chatroom'),
        ('core', '0006_add_duplicate_status'),
    ]

    operations = [
    ]
