# Generated by Django 5.2.3 on 2025-08-30 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_integration_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='integration',
            unique_together=set(),
        ),
    ]
