# Generated by Django 5.2.3 on 2026-04-05 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_add_duplicate_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='contenthash',
            name='embedding',
            field=models.JSONField(blank=True, help_text='Cached embedding vector for this content', null=True),
        ),
        migrations.AddIndex(
            model_name='contenthash',
            index=models.Index(fields=['app', 'content_type'], name='core_conten_app_id_456fce_idx'),
        ),
    ]
