# Generated by Django 5.2.3 on 2025-07-28 18:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_notificationprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppNotificationProfile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_notification_profiles', to='core.application')),
                ('notification_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_notification_profiles', to='core.notificationprofile')),
            ],
            options={
                'unique_together': {('application', 'notification_profile')},
            },
        ),
    ]
