# Generated by Django 5.2.3 on 2025-08-30 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_accountstatus'),
        ('core', '0007_alter_integration_unique_together'),
    ]

    operations = [
    ]
