# Generated by Django 5.2.3 on 2026-04-03 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_merge_20260403_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='prompt_config',
            field=models.JSONField(default=dict),
        ),
    ]
