# Generated by Django 5.2.3 on 2025-06-30 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_message_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgebase',
            name='source_type',
            field=models.CharField(choices=[('youtube', 'YouTube'), ('url', 'URL'), ('file', 'File'), ('text', 'Text')], default='file', max_length=20),
        ),
        migrations.AlterField(
            model_name='knowledgebase',
            name='path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
