# Generated by Django 5.2.3 on 2025-07-30 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_appnotificationprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationprofile',
            name='name',
            field=models.CharField(default='Unnamed', max_length=255),
            preserve_default=False,
        ),
    ]
