# Generated by Django 5.2.3 on 2026-04-05 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_add_embedding_cache_to_content_hash'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='contenthash',
            unique_together={('app', 'content_hash', 'content_type')},
        ),
        migrations.AddIndex(
            model_name='contenthash',
            index=models.Index(fields=['app', 'content_hash', 'content_type'], name='core_conten_app_id_598822_idx'),
        ),
    ]
