# Generated by Django 5.2.3 on 2025-08-04 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_integration'),
        ('core', '0008_notificationprofile_name'),
    ]

    operations = [
    ]
