# Generated by Django 5.2.3 on 2025-07-02 17:21

import django.db.models.deletion
import secrets
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_ingestedchunk'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='APIToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('key', models.CharField(default=secrets.token_urlsafe, max_length=64, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_root', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_tokens', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permissions', models.JSONField(default=dict)),
                ('api_token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_permissions', to='core.apitoken')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='token_permissions', to='core.application')),
            ],
            options={
                'unique_together': {('api_token', 'application')},
            },
        ),
    ]
