# Generated by Django 5.2.3 on 2025-09-05 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_accountstatus_created_at_accountstatus_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountstatus',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
