# Generated by Django 5.2.3 on 2026-02-27 17:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_aiprovider_delete_basemodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aiprovider',
            old_name='key',
            new_name='provider_api_key',
        ),
        migrations.AddField(
            model_name='aiprovider',
            name='base_url',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aiprovider',
            name='is_builtin',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
