# Generated by Django 5.2.3 on 2026-02-27 18:06

import core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_rename_key_aiprovider_provider_api_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiprovider',
            name='provider_api_key',
            field=core.fields.EncryptedCharField(max_length=1000),
        ),
    ]
