# Generated by Django 5.2.3 on 2026-03-01 18:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_aiprovider_provider_api_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppAIProvider',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('context', models.CharField(default='default', max_length=50)),
                ('capability', models.CharField(default='text', max_length=50)),
                ('priority', models.PositiveIntegerField(default=100)),
                ('external_model_id', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ai_provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application_configs', to='core.aiprovider')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_provider_configs', to='core.application')),
            ],
            options={
                'ordering': ['context', 'capability', 'priority'],
            },
        ),
    ]
