# Generated by Django 5.2.3 on 2026-03-04 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_appaiprovider'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aiprovider',
            options={'ordering': ['created_at']},
        ),
        migrations.AddField(
            model_name='appaiprovider',
            name='metadata',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appaiprovider',
            name='context',
            field=models.CharField(max_length=50),
        ),
    ]
