# Generated by Django 5.2.3 on 2026-03-04 17:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_remove_aiprovider_base_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiprovider',
            name='base_url',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
