# Generated by Django 5.2.3 on 2026-03-04 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_aiprovider_base_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aiprovider',
            name='base_url',
        ),
    ]
