# Generated by Django 5.2.3 on 2026-03-12 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_aiprovidermodels'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='ai_provider_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.aiprovider'),
        ),
        migrations.AddField(
            model_name='message',
            name='model',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
