# Generated by Django 5.2.3 on 2026-03-16 16:49

import core.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_aiprovidermodels'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notificationprofile',
            options={'ordering': ['name', 'created_at']},
        ),
        migrations.RemoveField(
            model_name='notificationprofile',
            name='_config',
        ),
        migrations.AddField(
            model_name='notificationprofile',
            name='config',
            field=core.fields.EncryptedJSONField(blank=True, default=dict, help_text='Encrypted configuration data for the notification provider'),
        ),
        migrations.AddField(
            model_name='notificationprofile',
            name='is_enabled',
            field=models.BooleanField(default=True, help_text='Whether this notification profile is currently active'),
        ),
        migrations.AddField(
            model_name='notificationprofile',
            name='metadata',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notificationprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='notificationprofile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='notificationprofile',
            name='name',
            field=models.CharField(help_text='Human-readable name for the notification profile', max_length=255),
        ),
        migrations.AlterField(
            model_name='notificationprofile',
            name='owner',
            field=models.ForeignKey(help_text='User who owns this notification profile', on_delete=django.db.models.deletion.CASCADE, related_name='notification_profiles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notificationprofile',
            name='type',
            field=models.CharField(help_text='Type of notification provider (email, slack, discord, whatsapp)', max_length=20),
        ),
        migrations.AddIndex(
            model_name='notificationprofile',
            index=models.Index(fields=['owner', 'type'], name='core_notifi_owner_i_85656b_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationprofile',
            index=models.Index(fields=['owner', 'is_enabled'], name='core_notifi_owner_i_1430e6_idx'),
        ),
    ]
