# Generated by Django 5.2.3 on 2026-03-12 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_message_ai_provider_id_message_model'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='ai_provider_id',
            new_name='ai_provider',
        ),
    ]
