# Generated by Django 5.2.3 on 2026-03-14 04:35

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_githubrepository_githubpullrequest_githubissue_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='githubissuecomment',
            name='github_id',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='githubpullrequest',
            name='github_id',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='githubissue',
            name='github_id',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='githubdiscussion',
            name='github_id',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='githubdiscussioncomment',
            name='github_id',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='githubprcomment',
            name='github_id',
            field=models.BigIntegerField(),
        ),
    ]
