# Generated by Django 5.2.3 on 2026-03-13 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_rename_ai_provider_id_message_ai_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='ai_provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.aiprovider'),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='model',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
