# Generated by Django 5.2.3 on 2026-03-15 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_remove_chatroom_chat_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroomparticipant',
            name='has_unread',
            field=models.BooleanField(default=False),
        ),
    ]
