# Generated by Django 5.2.3 on 2026-03-16 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_migrate_participant_identifier_prefixes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='mode',
            field=models.CharField(choices=[('ai', 'AI Mode'), ('direct', 'Direct Mode')], db_column='chat_mode', default='ai', max_length=10),
        ),
    ]
