# Generated by Django 5.2.3 on 2026-03-20 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_rename_chatroom_mode_column'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='ai_mode',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='platform',
            field=models.CharField(choices=[('dashboard', 'Dashboard'), ('widget', 'Widget')], default='dashboard', max_length=20),
        ),
    ]
