# Generated by Django 5.2.3 on 2026-03-20 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_message_platform_ai_mode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatroom',
            name='mode',
        ),
    ]
