# Generated by Django 5.2.3 on 2026-03-23 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_update_github_ids_to_bigint'),
        ('core', '0034_remove_chatroom_mode'),
    ]

    operations = [
    ]
