# Generated by Django 5.2.3 on 2026-03-28 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_merge_20260323_1011'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterField(
            model_name='githubrepository',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='knowledgebase',
            name='source_type',
            field=models.CharField(choices=[('url', 'URL'), ('file', 'File'), ('text', 'Text'), ('github', 'GitHub')], default='file', max_length=20),
        ),
    ]
