# Generated by Django 5.2.3 on 2026-03-25 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_merge_notification_and_chatroom'),
        ('core', '0036_alter_message_options_and_more'),
    ]

    operations = [
    ]
