# Generated by Django 5.2.3 on 2026-03-28 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_alter_message_options_and_more'),
        ('core', '0037_fix_github_repository_description_null'),
    ]

    operations = [
    ]
