# Generated by Django 5.2.3 on 2026-03-29 15:34

import core.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    # Must run outside a transaction so the DELETE's deferred FK triggers
    # are flushed before the ALTER TABLE executes.
    atomic = False

    dependencies = [
        ('core', '0040_migrate_integrations_data'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appintegration',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='integration',
            options={'ordering': ['created_at']},
        ),
        # Wipe all legacy integration data before making creator NOT NULL.
        # TRUNCATE ... CASCADE handles the full FK dependency tree automatically.
        migrations.RunSQL(
            sql="TRUNCATE core_integration CASCADE;",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AlterField(
            model_name='integration',
            name='creator',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name='integration',
            name='credentials',
            field=core.fields.EncryptedCharField(max_length=2000),
        ),
    ]
