# Generated by Django migration to refactor GitHub ingestion to generic version control

from django.db import migrations, models
import django.db.models.deletion
import uuid


def migrate_github_data_to_vc(apps, schema_editor):
    """Migrate data from GitHub-specific tables to generic version control tables."""

    # Get old and new models
    OldRepo = apps.get_model('core', 'GitHubRepository')
    OldIssue = apps.get_model('core', 'GitHubIssue')
    OldIssueComment = apps.get_model('core', 'GitHubIssueComment')
    OldPR = apps.get_model('core', 'GitHubPullRequest')
    OldPRComment = apps.get_model('core', 'GitHubPRComment')
    OldPRFile = apps.get_model('core', 'GitHubPRFile')

    NewRepo = apps.get_model('core', 'VCRepository')
    NewIssue = apps.get_model('core', 'VCIssue')
    NewIssueComment = apps.get_model('core', 'VCIssueComment')
    NewPR = apps.get_model('core', 'VCPullRequest')
    NewPRComment = apps.get_model('core', 'VCPRComment')
    NewPRFile = apps.get_model('core', 'VCPRFile')
    KnowledgeBase = apps.get_model('core', 'KnowledgeBase')

    # Map old repos to new repos
    repo_map = {}

    for old_repo in OldRepo.objects.all():
        new_repo = NewRepo.objects.create(
            uuid=old_repo.uuid,
            created_at=old_repo.created_at,
            updated_at=old_repo.updated_at,
            provider='github',
            external_id=str(old_repo.id),
            name=old_repo.name,
            repo_owner=old_repo.repo_owner,
            full_name=old_repo.full_name,
            description=old_repo.description,
            url=old_repo.url,
            is_private=old_repo.is_private,
            default_branch=old_repo.default_branch,
            last_ingested_at=old_repo.last_ingested_at,
            ingestion_status=old_repo.ingestion_status,
            metadata=old_repo.metadata,
            app_integration=old_repo.app_integration,
        )
        repo_map[old_repo.id] = new_repo

    # Migrate issues
    issue_map = {}
    for old_issue in OldIssue.objects.all():
        new_repo = repo_map.get(old_issue.repository_id)
        if new_repo:
            new_issue = NewIssue.objects.create(
                uuid=old_issue.uuid,
                external_id=str(old_issue.github_id),
                number=old_issue.number,
                title=old_issue.title,
                body=old_issue.body,
                state=old_issue.state,
                author=old_issue.author,
                author_association=old_issue.author_association,
                assignees=old_issue.assignees,
                labels=old_issue.labels,
                milestone=old_issue.milestone,
                locked=old_issue.locked,
                created_at_field=old_issue.created_at,
                updated_at_field=old_issue.updated_at,
                closed_at=old_issue.closed_at,
                url=old_issue.url,
                repository=new_repo,
            )
            issue_map[old_issue.id] = new_issue

    # Migrate issue comments
    for old_comment in OldIssueComment.objects.all():
        new_issue = issue_map.get(old_comment.issue_id)
        if new_issue:
            NewIssueComment.objects.create(
                uuid=old_comment.uuid,
                external_id=str(old_comment.github_id),
                body=old_comment.body,
                author=old_comment.author,
                author_association=old_comment.author_association,
                created_at_field=old_comment.created_at,
                updated_at_field=old_comment.updated_at,
                url=old_comment.url,
                issue=new_issue,
            )

    # Migrate pull requests
    pr_map = {}
    for old_pr in OldPR.objects.all():
        new_repo = repo_map.get(old_pr.repository_id)
        if new_repo:
            new_pr = NewPR.objects.create(
                uuid=old_pr.uuid,
                external_id=str(old_pr.github_id),
                number=old_pr.number,
                title=old_pr.title,
                body=old_pr.body,
                state=old_pr.state,
                author=old_pr.author,
                author_association=old_pr.author_association,
                assignees=old_pr.assignees,
                reviewers=old_pr.reviewers,
                labels=old_pr.labels,
                milestone=old_pr.milestone,
                head_branch=old_pr.head_branch,
                base_branch=old_pr.base_branch,
                merged=old_pr.merged,
                merged_at=old_pr.merged_at,
                merge_commit_sha=old_pr.merge_commit_sha,
                additions=old_pr.additions,
                deletions=old_pr.deletions,
                changed_files=old_pr.changed_files,
                created_at_field=old_pr.created_at,
                updated_at_field=old_pr.updated_at,
                closed_at=old_pr.closed_at,
                url=old_pr.url,
                repository=new_repo,
            )
            pr_map[old_pr.id] = new_pr

    # Migrate PR comments
    for old_comment in OldPRComment.objects.all():
        new_pr = pr_map.get(old_comment.pull_request_id)
        if new_pr:
            NewPRComment.objects.create(
                uuid=old_comment.uuid,
                external_id=str(old_comment.github_id),
                body=old_comment.body,
                author=old_comment.author,
                author_association=old_comment.author_association,
                created_at_field=old_comment.created_at,
                updated_at_field=old_comment.updated_at,
                url=old_comment.url,
                pull_request=new_pr,
            )

    # Migrate PR files
    for old_file in OldPRFile.objects.all():
        new_pr = pr_map.get(old_file.pull_request_id)
        if new_pr:
            NewPRFile.objects.create(
                uuid=old_file.uuid,
                filename=old_file.filename,
                status=old_file.status,
                additions=old_file.additions,
                deletions=old_file.deletions,
                changes=old_file.changes,
                patch=old_file.patch,
                blob_url=old_file.blob_url,
                raw_url=old_file.raw_url,
                contents_url=old_file.contents_url,
                pull_request=new_pr,
            )

    # Update KnowledgeBase entries
    for kb in KnowledgeBase.objects.filter(source_type='github'):
        kb.source_type = 'version_control'
        metadata = kb.metadata or {}
        metadata['provider'] = 'github'
        metadata['source'] = 'version_control'
        kb.metadata = metadata
        kb.save()


def reverse_migrate_vc_to_github(apps, schema_editor):
    """Reverse migration - not fully implemented for safety."""
    pass


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0041_alter_appintegration_options_and_more'),
    ]

    operations = [
        # Create VCRepository
        migrations.CreateModel(
            name='VCRepository',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(choices=[('github', 'GitHub'), ('gitlab', 'GitLab'), ('bitbucket', 'Bitbucket'), ('gitea', 'Gitea'), ('other', 'Other')], default='github', max_length=20)),
                ('external_id', models.CharField(blank=True, help_text='Provider-specific repository ID', max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('repo_owner', models.CharField(max_length=255)),
                ('full_name', models.CharField(max_length=511)),
                ('description', models.TextField(blank=True, null=True)),
                ('url', models.URLField()),
                ('is_private', models.BooleanField(default=False)),
                ('default_branch', models.CharField(default='main', max_length=100)),
                ('last_ingested_at', models.DateTimeField(blank=True, null=True)),
                ('ingestion_status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('app_integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vc_repositories', to='core.appintegration')),
            ],
            options={'ordering': ['-created_at']},
        ),
        migrations.AddIndex(
            model_name='vcrepository',
            index=models.Index(fields=['full_name'], name='core_vcrepo_full_na_6f8f7d_idx'),
        ),
        migrations.AddIndex(
            model_name='vcrepository',
            index=models.Index(fields=['app_integration'], name='core_vcrepo_app_int_7c3a8e_idx'),
        ),
        migrations.AddIndex(
            model_name='vcrepository',
            index=models.Index(fields=['ingestion_status'], name='core_vcrepo_ingest_9d2a1b_idx'),
        ),
        migrations.AddIndex(
            model_name='vcrepository',
            index=models.Index(fields=['provider'], name='core_vcrepo_provid_a1b2c3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='vcrepository',
            unique_together={('app_integration', 'full_name', 'provider')},
        ),

        # Create VCIssue
        migrations.CreateModel(
            name='VCIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('external_id', models.CharField(help_text='Provider-specific issue ID', max_length=255)),
                ('number', models.IntegerField()),
                ('title', models.CharField(max_length=1024)),
                ('body', models.TextField(blank=True)),
                ('state', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], max_length=20)),
                ('author', models.CharField(max_length=255)),
                ('author_association', models.CharField(blank=True, max_length=50)),
                ('assignees', models.JSONField(blank=True, default=list)),
                ('labels', models.JSONField(blank=True, default=list)),
                ('milestone', models.JSONField(blank=True, null=True)),
                ('locked', models.BooleanField(default=False)),
                ('created_at_field', models.DateTimeField(db_column='created_at_source')),
                ('updated_at_field', models.DateTimeField(db_column='updated_at_source')),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('url', models.URLField()),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='core.vcrepository')),
            ],
            options={'ordering': ['-created_at_field']},
        ),
        migrations.AlterUniqueTogether(
            name='vcissue',
            unique_together={('repository', 'external_id')},
        ),
        migrations.AddIndex(
            model_name='vcissue',
            index=models.Index(fields=['repository', 'state'], name='core_vcissue_repo_state_idx'),
        ),

        # Create VCIssueComment
        migrations.CreateModel(
            name='VCIssueComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('external_id', models.CharField(help_text='Provider-specific comment ID', max_length=255)),
                ('body', models.TextField()),
                ('author', models.CharField(max_length=255)),
                ('author_association', models.CharField(blank=True, max_length=50)),
                ('created_at_field', models.DateTimeField(db_column='created_at_source')),
                ('updated_at_field', models.DateTimeField(db_column='updated_at_source')),
                ('url', models.URLField()),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='core.vcissue')),
            ],
            options={'ordering': ['created_at_field']},
        ),
        migrations.AlterUniqueTogether(
            name='vcissuecomment',
            unique_together={('issue', 'external_id')},
        ),

        # Create VCPullRequest
        migrations.CreateModel(
            name='VCPullRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('external_id', models.CharField(help_text='Provider-specific PR/MR ID', max_length=255)),
                ('number', models.IntegerField()),
                ('title', models.CharField(max_length=1024)),
                ('body', models.TextField(blank=True)),
                ('state', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('merged', 'Merged')], max_length=20)),
                ('author', models.CharField(max_length=255)),
                ('author_association', models.CharField(blank=True, max_length=50)),
                ('assignees', models.JSONField(blank=True, default=list)),
                ('reviewers', models.JSONField(blank=True, default=list)),
                ('labels', models.JSONField(blank=True, default=list)),
                ('milestone', models.JSONField(blank=True, null=True)),
                ('head_branch', models.CharField(max_length=255)),
                ('base_branch', models.CharField(max_length=255)),
                ('merged', models.BooleanField(default=False)),
                ('merged_at', models.DateTimeField(blank=True, null=True)),
                ('merge_commit_sha', models.CharField(blank=True, max_length=40)),
                ('additions', models.IntegerField(default=0)),
                ('deletions', models.IntegerField(default=0)),
                ('changed_files', models.IntegerField(default=0)),
                ('created_at_field', models.DateTimeField(db_column='created_at_source')),
                ('updated_at_field', models.DateTimeField(db_column='updated_at_source')),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('url', models.URLField()),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pull_requests', to='core.vcrepository')),
            ],
            options={'ordering': ['-created_at_field']},
        ),
        migrations.AlterUniqueTogether(
            name='vcpullrequest',
            unique_together={('repository', 'external_id')},
        ),

        # Create VCPRComment
        migrations.CreateModel(
            name='VCPRComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('external_id', models.CharField(help_text='Provider-specific comment ID', max_length=255)),
                ('body', models.TextField()),
                ('author', models.CharField(max_length=255)),
                ('author_association', models.CharField(blank=True, max_length=50)),
                ('created_at_field', models.DateTimeField(db_column='created_at_source')),
                ('updated_at_field', models.DateTimeField(db_column='updated_at_source')),
                ('url', models.URLField()),
                ('pull_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='core.vcpullrequest')),
            ],
            options={'ordering': ['created_at_field']},
        ),
        migrations.AlterUniqueTogether(
            name='vcprcomment',
            unique_together={('pull_request', 'external_id')},
        ),

        # Create VCPRFile
        migrations.CreateModel(
            name='VCPRFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('filename', models.CharField(max_length=1024)),
                ('status', models.CharField(choices=[('added', 'Added'), ('modified', 'Modified'), ('removed', 'Removed'), ('renamed', 'Renamed')], max_length=20)),
                ('additions', models.IntegerField(default=0)),
                ('deletions', models.IntegerField(default=0)),
                ('changes', models.IntegerField(default=0)),
                ('patch', models.TextField(blank=True)),
                ('blob_url', models.URLField(blank=True)),
                ('raw_url', models.URLField(blank=True)),
                ('contents_url', models.URLField(blank=True)),
                ('pull_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='core.vcpullrequest')),
            ],
            options={'ordering': ['filename']},
        ),
        migrations.AlterUniqueTogether(
            name='vcprfile',
            unique_together={('pull_request', 'filename')},
        ),

        # Run data migration
        migrations.RunPython(migrate_github_data_to_vc, reverse_migrate_vc_to_github),
    ]
