# Generated by Django 5.2.3 on 2026-03-31 15:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_alter_appintegration_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integration',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='CustomToolRecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('url_schema', models.TextField()),
                ('is_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('app_integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_tools', to='core.appintegration')),
            ],
        ),
        migrations.CreateModel(
            name='ToolConfig',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('tool_id', models.CharField(max_length=255)),
                ('is_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('app_integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tool_configs', to='core.appintegration')),
            ],
            options={
                'unique_together': {('app_integration', 'tool_id')},
            },
        ),
    ]
