# Generated by Django 5.2.3 on 2026-03-31 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_alter_integration_id_customtoolrecord_toolconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='toolconfig',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='toolconfig',
            name='is_builtin',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='toolconfig',
            name='title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='toolconfig',
            name='url_schema',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.DeleteModel(
            name='CustomToolRecord',
        ),
    ]
