# Generated by Django 5.2.3 on 2026-03-30 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_refactor_github_to_version_control'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vcissue',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='vcissuecomment',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='vcprcomment',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='vcpullrequest',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameIndex(
            model_name='vcissue',
            new_name='core_vcissu_reposit_0746d1_idx',
            old_name='core_vcissue_repo_state_idx',
        ),
        migrations.RenameIndex(
            model_name='vcrepository',
            new_name='core_vcrepo_full_na_d7d75b_idx',
            old_name='core_vcrepo_full_na_6f8f7d_idx',
        ),
        migrations.RenameIndex(
            model_name='vcrepository',
            new_name='core_vcrepo_app_int_61b548_idx',
            old_name='core_vcrepo_app_int_7c3a8e_idx',
        ),
        migrations.RenameIndex(
            model_name='vcrepository',
            new_name='core_vcrepo_ingesti_6bce16_idx',
            old_name='core_vcrepo_ingest_9d2a1b_idx',
        ),
        migrations.RenameIndex(
            model_name='vcrepository',
            new_name='core_vcrepo_provide_314fdd_idx',
            old_name='core_vcrepo_provid_a1b2c3_idx',
        ),
        migrations.RemoveField(
            model_name='vcissue',
            name='created_at_field',
        ),
        migrations.RemoveField(
            model_name='vcissue',
            name='updated_at_field',
        ),
        migrations.RemoveField(
            model_name='vcissuecomment',
            name='created_at_field',
        ),
        migrations.RemoveField(
            model_name='vcissuecomment',
            name='updated_at_field',
        ),
        migrations.RemoveField(
            model_name='vcprcomment',
            name='created_at_field',
        ),
        migrations.RemoveField(
            model_name='vcprcomment',
            name='updated_at_field',
        ),
        migrations.RemoveField(
            model_name='vcpullrequest',
            name='created_at_field',
        ),
        migrations.RemoveField(
            model_name='vcpullrequest',
            name='updated_at_field',
        ),
        migrations.AddField(
            model_name='vcissue',
            name='metadata',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vcissuecomment',
            name='metadata',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vcprcomment',
            name='metadata',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vcprfile',
            name='metadata',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vcpullrequest',
            name='metadata',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='integration',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='vcissue',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='vcissue',
            name='updated_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='vcissuecomment',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='vcissuecomment',
            name='updated_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='vcprcomment',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='vcprcomment',
            name='updated_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='vcpullrequest',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='vcpullrequest',
            name='updated_at',
            field=models.DateTimeField(),
        ),
        migrations.AddIndex(
            model_name='vcissue',
            index=models.Index(fields=['external_id'], name='core_vcissu_externa_82d36f_idx'),
        ),
        migrations.AddIndex(
            model_name='vcissue',
            index=models.Index(fields=['created_at'], name='core_vcissu_created_b0d04a_idx'),
        ),
        migrations.AddIndex(
            model_name='vcissuecomment',
            index=models.Index(fields=['issue', 'created_at'], name='core_vcissu_issue_i_b79f4a_idx'),
        ),
        migrations.AddIndex(
            model_name='vcissuecomment',
            index=models.Index(fields=['external_id'], name='core_vcissu_externa_afe0be_idx'),
        ),
        migrations.AddIndex(
            model_name='vcprcomment',
            index=models.Index(fields=['pull_request', 'created_at'], name='core_vcprco_pull_re_95584f_idx'),
        ),
        migrations.AddIndex(
            model_name='vcprcomment',
            index=models.Index(fields=['external_id'], name='core_vcprco_externa_38e8d6_idx'),
        ),
        migrations.AddIndex(
            model_name='vcprfile',
            index=models.Index(fields=['pull_request', 'status'], name='core_vcprfi_pull_re_02fa3c_idx'),
        ),
        migrations.AddIndex(
            model_name='vcprfile',
            index=models.Index(fields=['filename'], name='core_vcprfi_filenam_eb41cb_idx'),
        ),
        migrations.AddIndex(
            model_name='vcpullrequest',
            index=models.Index(fields=['repository', 'state'], name='core_vcpull_reposit_6d4494_idx'),
        ),
        migrations.AddIndex(
            model_name='vcpullrequest',
            index=models.Index(fields=['external_id'], name='core_vcpull_externa_3c33cb_idx'),
        ),
        migrations.AddIndex(
            model_name='vcpullrequest',
            index=models.Index(fields=['created_at'], name='core_vcpull_created_865647_idx'),
        ),
        migrations.AddIndex(
            model_name='vcpullrequest',
            index=models.Index(fields=['merged'], name='core_vcpull_merged_23d1fe_idx'),
        ),
    ]
