#!/bin/bash

# GitHub API - Get Issue Comments
# Usage: ./get_issue_comments.sh owner repo issue_number [page] [per_page]

OWNER=${1:-"owner"}
REPO=${2:-"repo"}
ISSUE_NUMBER=${3:-"1"}
PAGE=${4:-"1"}
PER_PAGE=${5:-"100"}
TOKEN=${GITHUB_TOKEN:-"your_github_token_here"}

curl -X GET \
  -H "Authorization: Bearer ${TOKEN}" \
  -H "Accept: application/vnd.github+json" \
  -H "X-GitHub-Api-Version: 2022-11-28" \
  -H "User-Agent: Ch8r-GitHub-Ingestion/1.0" \
  "https://api.github.com/repos/${OWNER}/${REPO}/issues/${ISSUE_NUMBER}/comments?page=${PAGE}&per_page=${PER_PAGE}"
